In [6]:
import numpy as np

In [8]:
# read from a csv file
filename = '../records/2018-04-25 03:38:29.377676.csv'
data = np.genfromtxt(filename, delimiter=',')

In [19]:
len(data[:,0:2])

3857

In [29]:
acc = data[4:,0:3]

In [47]:
time_array = data[4:,-1]

In [28]:
len(time_array)

3853

In [ ]:
mean_acc = acc

In [42]:
acc

array([[ 0.01, -0.13, -1.11],
       [-0.  , -0.15, -1.11],
       [ 0.01, -0.12, -1.11],
       ...,
       [-0.73,  0.62,  0.23],
       [-0.73,  0.61,  0.23],
       [-0.72,  0.6 ,  0.2 ]])

In [43]:
acc**2

array([[1.0000e-04, 1.6900e-02, 1.2321e+00],
       [0.0000e+00, 2.2500e-02, 1.2321e+00],
       [1.0000e-04, 1.4400e-02, 1.2321e+00],
       ...,
       [5.3290e-01, 3.8440e-01, 5.2900e-02],
       [5.3290e-01, 3.7210e-01, 5.2900e-02],
       [5.1840e-01, 3.6000e-01, 4.0000e-02]])

In [44]:
acc_mag = acc.sum(axis=1)

In [45]:
acc_mag

array([-1.23, -1.26, -1.22, ...,  0.12,  0.11,  0.08])

In [48]:
time_array

array([2.15802200e+00, 2.65881400e+00, 3.16334000e+00, ...,
       1.72621248e+04, 1.72626330e+04, 1.72631426e+04])